config/routes.rb
Rails.application.routes.draw do
  root 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  resources :users, only: [:create, :show] do
    member do
      get :following, :followers
    end
  end
  resources :messages, only: :create
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :message
  validates :message, uniqueness: { scope: :user }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :likes
  validates :text,
            presence: true,
            length: { minimum: 1, maximum: 300 }

  default_scope { order(created_at: :desc) }

  def self.feed(user, current_user:)
    users_liked = 'SELECT user_id FROM likes WHERE likes.message_id = messages.id'
    condition = "#{current_user.id} IN (#{users_liked})"

    like_id_condition = "user_id = #{current_user.id} AND message_id = messages.id"
    get_like_id = "SELECT likes.id FROM likes WHERE #{like_id_condition}"

    current_user_liked = "CASE WHEN #{condition} THEN TRUE ELSE FALSE END AS liked"
    like_id = "CASE WHEN #{condition} THEN (#{get_like_id}) ELSE NULL END AS like_id"
    num_likes = '(SELECT COUNT(*) FROM likes WHERE message_id = messages.id) AS num_likes'

    if user == current_user
      following_ids = 'SELECT followed_id FROM relationships WHERE follower_id = :user_id'
      Message
        .where("user_id IN (#{following_ids}) OR user_id = :user_id",
               user_id: user.id)
        .includes(user: :photo_attachment)
        .select("messages.*, #{current_user_liked}, #{like_id}, #{num_likes}")
    else
      user.messages
        .includes(user: :photo_attachment)
        .select("messages.*, #{current_user_liked}, #{like_id}, #{num_likes}")
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :follower, uniqueness: { scope: :followed }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username,
            presence: true,
            length: { minimum: 4, maximum: 30 },
            uniqueness: true
  validates :fullname,
            presence: true,
            length: { minimum: 4, maximum: 50 }

  has_many :messages
  has_many :following_relationships,
           class_name: 'Relationship',
           foreign_key: 'follower_id',
           dependent: :destroy
  has_many :following,
           through: :following_relationships,
           source: :followed
  has_many :follower_relationships,
           class_name: 'Relationship',
           foreign_key: 'followed_id',
           dependent: :destroy
  has_many :followers,
           through: :follower_relationships
  has_many :likes
  has_one_attached :photo
  has_one_attached :coverimage

  def follow(other)
    following << other
  end

  def unfollow(other)
    following.delete(other)
  end

  def following?(other)
    following.where('followed_id = ?', other.id).exists?
  end

  def relationship_with(user)
    Relationship.find_by(follower_id: id, followed_id: user.id)
  end

  def like_message(message)
    message.likes.create(user_id: id)
  end

  def undo_like(message)
    Like.find_by(user_id: id, message_id: message.id).destroy
  end

  def photo_path
    photo.attached? ? photo : 'default_avatar.png'
  end

  def coverimage_path
    coverimage.attached? ? coverimage : 'default_cover.jpg'
  end

  def users_to_follow
    following_ids = 'SELECT followed_id FROM relationships WHERE follower_id = :user_id'
    User
      .with_attached_photo
      .where("id NOT IN (#{following_ids}) AND id != :user_id", user_id: id)
      .order(created_at: :desc)
      .limit(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  private

  def current_user
    return nil if cookies.signed[:user_id].nil?

    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorize
    redirect_to login_url if current_user.nil?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authorize, only: %i[create destroy]

  def create
    message = Message.find(params[:message_id])
    current_user.like_message(message)
    redirect_back(fallback_location: root_url)
  end

  def destroy
    message = Message.find(params[:message_id])
    like = Like.find(params[:id])
    like.user.undo_like(message)
    redirect_back(fallback_location: root_url)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authorize, only: :create

  def create
    message = current_user.messages.build(message_params)
    if message.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path,
                    flash: { danger: message.errors.full_messages.join(', ') })
    end
  end

  private

  def message_params
    params.require(:message).permit(:text)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authorize, only: %i[create destroy]

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new(); end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user
      cookies.signed[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:danger] = "User doesn't exist!"
      render 'new'
    end
  end

  def destroy
    cookies.delete(:user_id)
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: %i[show following followers]

  def show
    @user = params[:id].nil? ? current_user : User.find(params[:id])
    @feed = if @user == current_user
              Message.feed(@user, current_user: @user)
            else
              Message.feed(@user, current_user: current_user)
            end
    @logged_in_user = @user == current_user
    @users_list = if @logged_in_user
                    @user.users_to_follow
                  else
                    @user.followers
                  end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      cookies.signed[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  def following
    @user = User.find(params[:id])
    @title = "#{@user.fullname} is following"
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @title = "#{@user.fullname}'s followers"
    @users = @user.followers
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:username, :fullname, :photo, :coverimage)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def stats_color(user)
    current_user == user ? 'stat-num-self' : 'stat-num-other'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | TechPodium</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/flashing_alert' %>
      <%= yield %>
    </div>
  <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/likes/_like_form.html.erb
<div class="message-like">
  <% if message.num_likes > 0 %>
    <span class="num-likes text-muted"><%= message.num_likes %></span>&nbsp;&nbsp;&nbsp;
  <% end %>
  <div class="like-form">
    <% if message.liked %>
      <%= form_tag("/likes/#{message.like_id}", method: :delete) do %>
        <%= hidden_field_tag :message_id, message.id %>
        <%= submit_tag "<3", class: "btn btn-primary" %>
      <% end %>
    <% else %>
      <%= form_for current_user.likes.build do |f| %>
        <%= hidden_field_tag :message_id, message.id %>
        <%= f.submit "<3", class: "btn btn-outline-secondary" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/messages/_feed.html.erb
<div class="message-feed mx-3">
  <% if messages.any? %>
    <ul>
      <%= render partial: 'messages/message', collection: messages %>
    </ul>
  <% else %>
    <h4 class="text-primary">Nothing in the feed yet.</h4>
  <% end %>
</div>

app/views/messages/_message.html.erb
<li>
  <div id="message-<%= message.id %>" class="card border-0">
    <div class="row no-gutters">
      <div class="col-3">
        <%= image_tag message.user.photo_path, class: "card-img" %>
      </div>
      <div class="col-9">
        <div class="card-body">
          <div class='message-attribution' >
            <%= link_to message.user.fullname, user_path(message.user), class: 'message-author' %>
            <small class='message-date text-muted'> <%= time_ago_in_words(message.created_at) %></small>
          </div>
          <p class="message-text">
            <%= message.text %>
          </p>
          <div class='message-liking'>
            <%= render partial: 'likes/like_form', locals: { message: message }%>
          </div>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/messages/_message_form.html.erb
<div id="messaging-form" class="clearfix my-4 mx-3 rounded">
  <%= form_for(user.messages.new) do |f| %>
    <div class="form-group">
      <p class="font-weight-bold text-uppercase">Say something</p>
      <%= f.text_area :text, size: '30x3', placeholder: 'Compose new message', class: 'form-control' %>
    </div>

    <div id="form-submit">
      <%= f.submit 'Message', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashing_alert.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/shared/_navigation.html.erb
<div id="photo-box">
  <%= image_tag(current_user.photo_path, size: "80x80") %>
  <h4 class="ml-2"><%= current_user.fullname %></h4>
</div>
<div class="stats">
  <%= render partial: 'follow_stats', locals: { user: current_user } %>
</div>
<div id="cu-links">
  <%= link_to "Home", root_path, class: "btn btn-outline-light btn-lg" %>
  <%= link_to "Log out", logout_path, method: :delete, class: "btn btn-outline-light btn-lg" %>
</div>

app/views/users/_follow_form.html.erb
<% if current_user != user %>
  <div id="follow-form">
    <% if current_user.following?(user) %>
      <%= form_for(current_user.relationship_with(user), html: { method: :delete }) do |f| %>
        <%= f.submit "Unfollow", class: "btn btn-outline-secondary"%>
      <% end %>
    <% else %>
      <%= form_for(current_user.following_relationships.build) do |f| %>
        <%= hidden_field_tag :followed_id, user.id %>
        <%= f.submit "Follow", class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/_follow_stats.html.erb
<div class="stat ">
  <%= link_to(following_user_path(user),
              id: "following-#{user.id}",
              class: "btn btn-light bg-transparent border-0") do %>
    <div class="<%= stats_color(user) %>"><%= user.following.count %></div>
    <div class="stat-text font-weight-bold">Following</div>
  <% end %>
</div>
<div class="stat">
  <%= link_to(followers_user_path(user),
              id: "followers-#{user.id}",
              class: "btn btn-light bg-transparent border-0") do %>
    <% cnt = user.followers.count %>
    <div class="<%= stats_color(user) %>"><%= cnt %></div>
    <div class="stat-text font-weight-bold"><%= "Follower".pluralize(cnt) %></div>
  <% end %>
</div>

app/views/users/_user.html.erb
<li>
  <div id="user-<%= user.id %>" class="row ml-2 position-relative">
    <div class="user-photo">
      <%= image_tag(user.photo_path, size: "50x50", class: "rounded-circle") %>
    </div>
    <div class="ml-2 position-static">
      <div class="user-fullname">
        <strong><%= user.fullname %></strong>
      </div>
      <div class="user-username">
        <p>@<%= user.username %></p>
        <%= link_to "", user_path(user), class: "stretched-link" %>
      </div>
    </div>
  </div>
</li>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="row vh-100 align-items-center">
  <div class="col-md-6 col-md-offset-3 mx-auto bg-light">
    <h1 class="text-center">Sign up</h1>
    <%= form_for @user do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :fullname %>
        <%= f.text_field :fullname, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :photo, "Profile photo:" %>
        <%= f.file_field :photo %>
      </div>
      <div class="form-group">
        <%= f.label :coverimage, "Profile cover:" %>
        <%= f.file_field :coverimage %>
      </div>
      <%= f.submit "Sign up", class: "btn btn-primary w-100" %>
    <% end %>
    <p> Already registered? <%= link_to "Log in", login_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'Home') %>
<div class="row">
  <div class="col-3" id="left-tab">
    <%= render partial: 'shared/navigation', locals: { current_user: current_user } %>
  </div>
  <div class="col-9 flex-column">
    <div class="row">
      <div class="col-12" id="title-bar">
        <h3 class="text-light text-uppercase my-3">Tech-Podium</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-8 px-0" id="center-tab">
        <div class="title-bar"></div>
        <% if logged_in? && current_user == @user %>
          <%= render partial: 'messages/message_form', locals: { user: @user } %>
        <% else %>
          <div class="cover-image">
            <%= image_tag(@user.coverimage_path, class: "img-fluid") %>
          </div>
        <% end %>
        <%= render partial: 'messages/feed', locals: { messages: @feed } %>
      </div>
      <div class="col-4" id="right-tab">
        <div class="title-bar"></div>
        <div id="profile-info">
          <% if !@logged_in_user %>
            <%= image_tag @user.photo_path,
                          size: "80x80",
                          class: "d-block mx-auto rounded-circle" %>
            <h5><%= @user.fullname %></h5> 
            <p class="text-muted">@<%= @user.username %></p>
            <div class="stats">
              <div class="stat">
                <% cnt = @user.messages.count %>
                <div class="stat-num-other"><%= cnt %></div>
                <div class="stat-text font-weight-bold"><%= 'Message'.pluralize(cnt) %></div>
              </div>
              <%= render partial: 'follow_stats', locals: { user: @user } %>
            </div>
            <%= render partial: 'follow_form', locals: { user: @user } %>
          <% end %>
        </div>
        <div class="users-list">
          <% if @users_list.any? %>
            <% if @logged_in_user %>
              <h4>Users to follow:</h4>
            <% else %>
              <h4>Followed by:</h4>
            <% end %>
            <%= render partial: "user", collection: @users_list, as: :user %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <div class="col-3">
    <%= render partial: 'shared/navigation', locals: { current_user: current_user } %>
  </div>
  <div class="col-9">
    <h2><%= @title %></h2>
    <% if @users.any? %>
      <ul class="users-list">
        <%= render @users %>
      </ul>
    <% end %>
  </div>
</div>